# Generated by Django 2.2.2 on 2019-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aircraft_info',
            fields=[
                ('aircraft_serial_number', models.DecimalField(decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('aircraft_operator', models.TextField(verbose_name='飞机拥有者')),
                ('flight_cycles', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='飞行循环')),
                ('flight_hours', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='飞行小时')),
                ('record_time', models.DateField(verbose_name='飞行记录时间')),
            ],
            options={
                'verbose_name': '航空器信息',
                'verbose_name_plural': '航空器信息',
                'ordering': ('aircraft_serial_number',),
            },
        ),
        migrations.CreateModel(
            name='aircraft_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft_type_number', models.TextField(verbose_name='机型编号')),
            ],
            options={
                'verbose_name': '机型',
                'verbose_name_plural': '机型',
                'ordering': ('aircraft_type_number',),
            },
        ),
        migrations.CreateModel(
            name='ATA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.TextField(verbose_name='专业')),
                ('chapter', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='章')),
                ('section', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='节')),
                ('subject', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='题')),
            ],
            options={
                'verbose_name': 'ATA章节',
                'verbose_name_plural': 'ATA章节',
                'ordering': ('chapter', 'section', 'subject'),
            },
        ),
        migrations.CreateModel(
            name='event_list',
            fields=[
                ('internal_number', models.TextField(primary_key=True, serialize=False, verbose_name='内部编号')),
                ('attachment_info', models.TextField(verbose_name='附件信息')),
                ('corrective_action', models.TextField(verbose_name='纠正文本')),
                ('event_descrption', models.TextField(verbose_name='问题描述')),
                ('failure_number', models.TextField(verbose_name='故障编号')),
                ('failure_part_name', models.TextField(verbose_name='故障件名称')),
                ('failure_part_number', models.TextField(verbose_name='故障件件号')),
                ('flight_phase', models.TextField(verbose_name='飞行阶段')),
                ('handling_suggestion', models.TextField(verbose_name='问题关闭情况')),
                ('if_tech_question', models.BooleanField(default=False, verbose_name='是否技术问题')),
                ('occurrence_time', models.DateField(verbose_name='发生时间')),
                ('other_number', models.TextField(verbose_name='其他编号')),
                ('task_classification', models.TextField(verbose_name='任务分类')),
                ('task_number', models.TextField(verbose_name='任务编号')),
                ('troubleshooting', models.TextField(verbose_name='排故概况')),
            ],
            options={
                'verbose_name': '事件清单',
                'verbose_name_plural': '事件清单',
                'ordering': ('event_descrption', 'task_number'),
            },
        ),
    ]
