# Generated by Django 2.2.2 on 2019-09-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intra_type_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_list',
            new_name='event_info',
        ),
    ]
