# Generated by Django 2.2.2 on 2019-09-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intra_type_data', '0002_auto_20190922_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft_info',
            old_name='aircraft_operator',
            new_name='aircraft_owner',
        ),
        migrations.RenameField(
            model_name='aircraft_info',
            old_name='flight_cycles',
            new_name='cumulative_flight_cycles',
        ),
        migrations.RenameField(
            model_name='aircraft_info',
            old_name='flight_hours',
            new_name='cumulative_flight_hours',
        ),
        migrations.RemoveField(
            model_name='aircraft_info',
            name='record_time',
        ),
        migrations.AddField(
            model_name='aircraft_info',
            name='flight_character',
            field=models.TextField(default=None, verbose_name='飞行性质'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft_info',
            name='monthly_available_days',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=3, verbose_name='在用架日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft_info',
            name='record_date',
            field=models.DateField(default=None, verbose_name='记录时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraft_info',
            name='aircraft_serial_number',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='航空器注册号'),
        ),
    ]
