# Generated by Django 2.2.2 on 2019-09-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intra_type_data', '0003_auto_20190926_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft_info',
            name='aircraft_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_info_aircraft_type', to='intra_type_data.aircraft_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='ATA',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_info_ATA', to='intra_type_data.ATA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='aircraft_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_info_aircraft_info', to='intra_type_data.aircraft_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='detail_info_source',
            field=models.TextField(default=None, verbose_name='详细信息来源'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='event_state',
            field=models.TextField(default=None, verbose_name='问题关闭情况'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='failure_handling',
            field=models.TextField(default=None, verbose_name='故障处理'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_info',
            name='remarks',
            field=models.TextField(default=None, verbose_name='备注'),
            preserve_default=False,
        ),
    ]
