# Generated by Django 2.2.2 on 2019-09-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intra_type_data', '0004_auto_20190927_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_info',
            options={'ordering': ('event_description', 'task_number'), 'verbose_name': '事件清单', 'verbose_name_plural': '事件清单'},
        ),
        migrations.RenameField(
            model_name='event_info',
            old_name='event_descrption',
            new_name='event_description',
        ),
    ]
