# Generated by Django 2.2.2 on 2019-10-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intra_type_data', '0005_auto_20190927_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft_info',
            name='monthly_available_days',
        ),
        migrations.RemoveField(
            model_name='aircraft_info',
            name='record_date',
        ),
        migrations.AlterField(
            model_name='event_info',
            name='handling_suggestion',
            field=models.TextField(verbose_name='处理意见'),
        ),
    ]
