# Generated by Django 2.1.7 on 2019-08-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_data', '0004_auto_20190824_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='abnormal_flight_report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(max_length=8, verbose_name='航班号')),
                ('occurrence_time', models.DateField(verbose_name='发生时间')),
                ('occurrence_place', models.CharField(max_length=8, verbose_name='发生地点')),
                ('occurrence_phase', models.CharField(max_length=8, verbose_name='发生阶段')),
                ('failure_report_number', models.CharField(max_length=8, verbose_name='故障报告编号')),
                ('failure_description', models.TextField(verbose_name='故障描述')),
                ('delay_hours', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='延误时间/分钟')),
                ('consequence', models.TextField(verbose_name='后果')),
                ('part_replaced_name', models.CharField(max_length=8, verbose_name='拆换件名称')),
                ('part_replaced_number', models.CharField(max_length=8, verbose_name='拆换件件号')),
                ('part_replaced_serial_number', models.CharField(max_length=8, verbose_name='拆换件序号')),
                ('TSR', models.CharField(max_length=8)),
                ('TSN', models.CharField(max_length=8)),
                ('event_survey_summary', models.TextField(verbose_name='事件调查总结')),
                ('belong_to_region', models.CharField(max_length=8, verbose_name='所属区域')),
                ('wether_to_start', models.BooleanField(default=False, verbose_name='是否始发')),
                ('event_analysis', models.TextField(verbose_name='事件分析')),
                ('delay_quality', models.CharField(max_length=8, verbose_name='延误定性')),
                ('improvement_measures_resolutions', models.TextField(verbose_name='改进措施与决议')),
                ('departure_planned_time', models.DateField(verbose_name='计划起飞时间')),
                ('departure_actual_time', models.DateField(verbose_name='实际起飞时间')),
                ('major', models.CharField(max_length=8, verbose_name='专业')),
            ],
            options={
                'verbose_name': '航班不正常报告',
                'verbose_name_plural': '航班不正常报告',
                'ordering': ('delay_quality',),
            },
        ),
        migrations.RemoveField(
            model_name='adnormal_failure_report',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='adnormal_failure_report',
            name='ata',
        ),
        migrations.AlterModelOptions(
            name='aircraft_info',
            options={'ordering': ('aircraft',), 'verbose_name': '航空器信息', 'verbose_name_plural': '航空器信息'},
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_serial_number',
        ),
        migrations.RemoveField(
            model_name='aircraft_info',
            name='acmodel',
        ),
        migrations.AddField(
            model_name='aircraft_info',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_information_aircraft', to='type_data.aircraft'),
        ),
        migrations.AddField(
            model_name='record_of_part_replaced',
            name='replacement_work_type',
            field=models.CharField(max_length=100, null=True, verbose_name='拆换工作类型'),
        ),
        migrations.AlterField(
            model_name='record_of_part_replaced',
            name='replacement_type',
            field=models.CharField(max_length=100, verbose_name='拆换类型'),
        ),
        migrations.DeleteModel(
            name='adnormal_failure_report',
        ),
        migrations.AddField(
            model_name='abnormal_flight_report',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_flight_report_aircraft', to='type_data.aircraft'),
        ),
        migrations.AddField(
            model_name='abnormal_flight_report',
            name='ata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abnormal_flight_report_ata', to='type_data.ata'),
        ),
    ]
