# Generated by Django 2.1.7 on 2019-08-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_data', '0005_auto_20190824_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='engine_replacement_type',
        ),
        migrations.DeleteModel(
            name='engine_replacement_type',
        ),
    ]
