# Generated by Django 2.2.2 on 2019-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_data', '0008_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='death_toll',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='死亡人数'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='occurrence_time',
            field=models.DateField(verbose_name='事故时间'),
        ),
    ]
