# Generated by Django 2.2.2 on 2019-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_data', '0009_auto_20190918_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='aircraft',
        ),
        migrations.AddField(
            model_name='accident',
            name='aircraft_registration_number',
            field=models.TextField(default=None, verbose_name='航班注册号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accident',
            name='aircraft_type',
            field=models.TextField(default=None, verbose_name='机型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_package_information',
            name='achievement_hours',
            field=models.DateField(verbose_name='完工时间'),
        ),
    ]
