# Generated by Django 2.2.2 on 2019-09-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_platform', '0003_auto_20190824_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_address',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='data_source',
            name='acmodel',
        ),
        migrations.DeleteModel(
            name='accident',
        ),
        migrations.DeleteModel(
            name='data_address',
        ),
        migrations.DeleteModel(
            name='data_source',
        ),
    ]
